export const testIds = {
  HEADER: 'HEADER',
  USER_NAME: 'USER_NAME',
  COURSE_CARD: {
    TITLE: 'TITLE',
    DESCRIPTION: 'DESCRIPTION',
    AUTHORS: 'AUTHORS',
    DURATION: 'DURATION',
    CREATION_DATE: 'CREATION_DATE',
  },
};
