export const testIds = {
  HEADER: 'HEADER',
  USER_NAME: 'USER_NAME',
  COURSE_WRAPPER: 'COURSE_WRAPPER',
  COURSE_FORM: 'COURSE_FORM',
  AUTHOR_ITEM: 'AUTHOR_ITEM',
  ADD_AUTHOR_BTN: 'ADD_AUTHOR_BTN',
  COURSE_CARD: {
    CARD: 'CARD',
    TITLE: 'TITLE',
    DESCRIPTION: 'DESCRIPTION',
    AUTHORS: 'AUTHORS',
    DURATION: 'DURATION',
    CREATION_DATE: 'CREATION_DATE',
  },
  ADD_BTN: 'ADD_BTN',
};
